### ISSUE TITLE
fastavro._reader renamed to fastavro.read._read

### ISSUE THREAD

**Issue by nirizr** [rmax/dask-avro#2]
I have just installed fastavro, version is 0.17.2.
fastavro does not have the `_reader` attribute used in dask-avro and instead have it named `fastavro.read._read`. Changing that name works fine, but otherwise an exception is thrown.

**Comment by rmax** [comment]
Thank you for the report. I dig into it and there is an issue with the internal [_iter_avro](https://github.com/tebeka/fastavro/blob/master/fastavro/_read.pyx#L609) function which expects a ``ReaderBase`` argument which is not exposed to python.

For now I have made a quick release ``0.1.1`` requiring ``fastavro<0.16``.

**Comment by nirizr** [comment]
Hi, I eventually managed to get it working using `fastavro._read_py._iter_avro`.

In a previous version a co-worker needed to use `fastavro._reader_py._iter_avro`

**Comment by rmax** [comment]
Ideally we would like to use the cython-optimized `_iter_avro` version. That's a valid workaround, though.

**Comment by nirizr** [comment]
Any insight into how would I be able to achieve that?

Thanks!

**Comment by rmax** [comment]
The problem I saw is that [_iter_avro](https://github.com/tebeka/fastavro/blob/master/fastavro/_read.pyx#L626) expects a ``ReaderBase`` which is [not exposed to python](https://github.com/tebeka/fastavro/blob/master/fastavro/_read.pyx#L551).

**Comment by rmax** [comment]
Fixed in https://github.com/rmax/dask-avro/commit/c568ccfadd4f8467fe492d35919934ea38c48b52 and released [v0.2.0](https://pypi.org/project/dask-avro/0.2.0/).

**Comment by nirizr** [comment]
Thank you for the fast resolution!
